from django.urls import path
from .views import (
    BlogView,
    UserView,
    LikeView,
    check_blog_like_exists,
    CommentBlogView,
    CommentLikeView,
    check_comment_like_exists,
    get_blogs_for_user,
)

urlpatterns = [
    path("blogs/", BlogView.as_view(), name="get_all_blogs"),
    path("blogs/<pk>", BlogView.as_view(), name="get_blog_info"),
    path("create/", BlogView.as_view(), name="create_blog"),
    path("update/<pk>", BlogView.as_view(), name="update_blog"),
    path("delete/<pk>", BlogView.as_view(), name="delete_blog"),
    path("user/blogs/", get_blogs_for_user, name="get_blogs_for_user"),
    path("users/", UserView.as_view(), name="get_all_users"),
    path("users/<pk>", UserView.as_view(), name="get_user_details"),
    path("users/create/", UserView.as_view(), name="create_user"),
    path("likes/<blog_item_pk>", LikeView.as_view(), name="get_likes_for_blog"),
    path("likes/", LikeView.as_view(), name="get_all_likes"),
    path("likes/create/", LikeView.as_view(), name="create_like"),
    path("user_blog_like/<blog_id>", check_blog_like_exists, name="check_like_exists"),
    path("blog/<blog_item>/comments/", CommentBlogView.as_view(), name="get_blog_comments"),
    path("blogs/comments/", CommentBlogView.as_view(), name="get_all_comments"),
    path("blog/comment/create/", CommentBlogView.as_view(), name="create_blog_comment"),
    path("comment/<pk>/update/", CommentBlogView.as_view(), name="update_comment"),
    path("comment/<pk>/delete/", CommentBlogView.as_view(), name="delete_comment"),
    path("comments/likes/<comment_blog_item_pk>", CommentLikeView.as_view(), name="get_comment_likes"),
    path("comments/likes/", CommentLikeView.as_view(), name="get_all_comment_likes"),
    path("comments/likes/create/", CommentLikeView.as_view(), name="create_comment_like"),
    path("comment_blog_like/<comment_id>", check_comment_like_exists, name="check_comment_like"),
]
