# Generated by Django 4.0.3 on 2022-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='body',
            field=models.TextField(),
        ),
    ]
