# Generated by Django 4.0.3 on 2022-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
