# Generated by Django 4.0.3 on 2022-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogitem_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
